CREATE OR REPLACE VIEW V_LISTS_BOOKS (BOOK_TITLE, BOOK_RANK, BOOK_PUBLISHER, LIST_NAME, BESTSELLERS_DATE) AS (
SELECT 
 	F.value:title::STRING AS BOOK_TITLE,
    F.value:rank::INT AS BOOK_RANK,
    F.value:publisher::STRING AS BOOK_PUBLISHER,
    LIST_NAME::STRING,
	BESTSELLERS_DATE::DATE
 FROM V_LISTS ,
 Table(Flatten(V_LISTS.books)) F
)
